version: '3'
services:
    api:
        restart: always
        env_file: ./.env
        build: 
          dockerfile: Dockerfile
          context: ./
        depends_on:
          - mysql
        ports: 
          - '80:80'
        environment:
          DB_USERNAME: $DB_USERNAME
          DB_PWD: $DB_PWD
          DB_HOST: mysql
          DB: avo4cam
          JWT_SECRET: $JWT_SECRET
          JWT_SECRET_REFRESH: $JWT_SECRET_REFRESH
          MAIL_SERVICE: $MAIL_SERVICE
          MAIL_USER: $MAIL_USER@gmail.com
          MAIL_PASS: $MAIL_PASS
        stdin_open: true
        tty: true
    mysql:
      image: mysql:latest
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      env_file: ./.env
      environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_ROOT_PASSWORD
        MYSQL_USER: $MYSQL_ROOT_PASSWORD
        MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
      container_name: mysql-container
      volumes: 
        - ./sql/avo4cam.sql:/docker-entrypoint-initdb.d/avo4cam.sql 
      
