version: '3'
services:
    api:
        restart: always
        env_file: ./.env
        build: 
          dockerfile: Dockerfile
          context: ./
        depends_on:
          - mysql
        ports: 
          - '8080:80'
        environment:
          DB_USERNAME: $DB_USERNAME
          DB_PWD: $DB_PWD
          DB_HOST: mysql
          DB: avo4cam
          JWT_SECRET: $JWT_SECRET
          JWT_SECRET_REFRESH: $JWT_SECRET_REFRESH
          MAIL_SERVICE: $MAIL_SERVICE
          MAIL_USER: $MAIL_USER
          MAIL_PASS: $MAIL_PASS
          DATABASE_URL: $DATABASE_URL
          CLIENT_ID: $CLIENT_ID
          CLIENT_SECRET: $CLIENT_SECRET
          REDIRECT_URI: $REDIRECT_URI
          REFRESH_TOKEN: $REFRESH_TOKEN
        stdin_open: true
        tty: true
    mysql:
      image: mysql:latest
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      env_file: ./.env
      environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
      container_name: mysql-container
      #volumes: 
      #  - ./sql/avo4cam.sql:/docker-entrypoint-initdb.d/avo4cam.sql 
networks:
  default:
    external:
      name: avo4camerun-network
      
